# Generated by Django 5.2 on 2026-04-18 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='bookmarks', to='prompts.prompt')),
                ('user', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='prompt_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='likes', to='prompts.prompt')),
                ('user', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='prompt_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='promptbookmark',
            constraint=models.UniqueConstraint(fields=('user', 'prompt'), name='unique_prompt_bookmark'),
        ),
        migrations.AddConstraint(
            model_name='promptlike',
            constraint=models.UniqueConstraint(fields=('user', 'prompt'), name='unique_prompt_like'),
        ),
    ]
